// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnQF55rzic9jBlfA2xpBavbJbDyMGb3Js',
    appId: '1:1053131447262:web:7e0c82f3355335a7cb9b4f',
    messagingSenderId: '1053131447262',
    projectId: 'my-fller',
    authDomain: 'my-fller.firebaseapp.com',
    storageBucket: 'my-fller.firebasestorage.app',
    measurementId: 'G-FX39NEJ4E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGIxh2sBBjUr8Gw5DJ-UCFNv-i8AlrBws',
    appId: '1:1053131447262:android:b1a738f03dcea405cb9b4f',
    messagingSenderId: '1053131447262',
    projectId: 'my-fller',
    storageBucket: 'my-fller.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-k_3mbmy_QNQV87YWw8ajuDv8P2Fk8pA',
    appId: '1:1053131447262:ios:9877e44314359f2fcb9b4f',
    messagingSenderId: '1053131447262',
    projectId: 'my-fller',
    storageBucket: 'my-fller.firebasestorage.app',
    iosBundleId: 'com.example.myFiller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-k_3mbmy_QNQV87YWw8ajuDv8P2Fk8pA',
    appId: '1:1053131447262:ios:9877e44314359f2fcb9b4f',
    messagingSenderId: '1053131447262',
    projectId: 'my-fller',
    storageBucket: 'my-fller.firebasestorage.app',
    iosBundleId: 'com.example.myFiller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnQF55rzic9jBlfA2xpBavbJbDyMGb3Js',
    appId: '1:1053131447262:web:16cfd7d14e0c9521cb9b4f',
    messagingSenderId: '1053131447262',
    projectId: 'my-fller',
    authDomain: 'my-fller.firebaseapp.com',
    storageBucket: 'my-fller.firebasestorage.app',
    measurementId: 'G-3D1GKWX62D',
  );
}
