import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'NTN_Registration.dart';
import 'firebase_options.dart'; // This should be generated by FlutterFire CLI
import 'onbarding.dart';
import 'NTNfinder.dart';
import 'real_home.dart';
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Firebase Flutter App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home:  OnboardingScreen(),
    );
  }
}
